global:
  scrape_interval: 5s  # Intervalo padr√£o de coleta
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'microservice01'
    metrics_path: /metrics
    static_configs:
      - targets: ['microservice01:3000']


  - job_name: 'microservice02'
    metrics_path: /metrics
    static_configs:
      - targets: ['microservice02:3001']
